CREATE TABLE IF NOT EXISTS rooms (
  id UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
  name TEXT NOT NULL,
  host UUID REFERENCES AUTH.USERS ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT NOW(),
);

CREATE TABLE IF NOT EXISTS players (
  id UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
  roomId UUID REFERENCES rooms(id) ON DELETE CASCADE,
  user UUID REFERENCES AUTH.USERS ON DELETE CASCADE,
  nickname TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  heartbeat_at TIMESTAMP DEFAULT NOW(),
);
