DROP TABLE IF EXISTS games CASCADE;
DROP TABLE IF EXISTS players CASCADE;
DROP TABLE IF EXISTS messages CASCADE;

CREATE TABLE IF NOT EXISTS games (
  id UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
  address TEXT,
  name TEXT NOT NULL,
  host UUID REFERENCES AUTH.USERS ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT NOW(),
  heartbeat_at TIMESTAMP DEFAULT NOW(),
  is_playing BOOL DEFAULT FALSE,
  state JSONB
);
-- ALTER TABLE games ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS players (
  id UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
  uid UUID REFERENCES AUTH.USERS ON DELETE CASCADE,
  game_id UUID REFERENCES games(id) ON DELETE CASCADE,
  game_address TEXT,
  nickname TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  heartbeat_at TIMESTAMP DEFAULT NOW(),
  is_playing BOOL DEFAULT FALSE,
  state JSONB
);
-- ALTER TABLE players ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS messages (
  id UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
  game UUID REFERENCES games(id) ON DELETE CASCADE,
  sender UUID REFERENCES players(id) ON DELETE CASCADE,
  receiver UUID REFERENCES players(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT NOW(),
  data JSONB
);
-- ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
